### PR TITLE
Allowing empty accessibilityStates

### PR DESCRIPTION
**Pull request by fawcilize**
According to the documentation, https://facebook.github.io/react-native/docs/view#accessibilitystates: `You can provide one state, no state, or both states`. This is the case when a button may be unselected and enabled, like an inactive tab.

I'm not sure how to test this manually. I tried pointing my package.json to the commit hash, but it didn't seem to work. Maybe there is some bundling step I am missing? The automated tests pass though.

#45

### CODE REVIEW

**Comment by fawcilize** [comment]
It looks like the build failure is `The command "yarn install --frozen-lockfile" failed and exited with 1 during .` I'm not sure that's related to my change.

**Comment by ryan-roemer** [comment]
We're hitting a known package that doesn't support node6, but AFAICT our `yarn.lock` hasn't changed so this shouldn't be an issue.

I've restarted the `master` build to see if `master` is actually still passing here -- https://travis-ci.org/FormidableLabs/eslint-plugin-react-native-a11y/builds/451572370

**Comment by ryan-roemer** [comment]
OH WAIT. We don't commit `yarn.lock`. Hahaha. And `master` build I did right now is failing.

We should add a yarn.lock, and I've got a ticket for it: https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/issues/46

Once we get an ironed out `yarn.lock`, to address this issue here with the node6 package we should either:

- add a yarn resolution to a node6 compatible of the incompatible transitive dependency package; OR
- drop node6 from Travis CI (it's EOL'ed in April 2019 anyways)

**Comment by fawcilize** [comment]
Is there something I need to do here?

**Comment by anidel** [comment]
I would love to have this merged in. We're disabling the rule in all the files where we use `accessibilityStates`, so would be great to  have this fixed :)

**Comment by MoOx** [comment]
@fawcilize Could you merge conflict?

**Comment by fawcilize** [comment]
Has a green build now. Sorry for the delay.

**Comment by MoOx** [comment]
Would be nice to get this merged as this rule is currently kind of broken as the state is (since at least RN 0.45, probably before & forever) been an array of string, not a string

**Comment by kelset** [comment]
I'll ping @alex-saunders ;)

**Comment by alex-saunders** [comment]
Thanks for your work on this @fawcilize ! Merging now.

**Pull request merged**
