### PR TITLE
feature: allow eslint 8 as a peer dependency

### LINKED ISSUE #144: Adding eslint 8 as compatible peer dependency
```
warning " > eslint-plugin-react-native-a11y@3.2.1" has incorrect peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7".
```

Any blockers on adding eslint 8?

### PR DESCRIPTION
**Pull request by philihp**
Resolves #144

### CODE REVIEW

**Comment by thymikee** [comment]
Would be great to have this one warning less 👍🏼 And the plugin works fine with ESLint 8

**Comment by philihp** [comment]
RE #137, this was updated in the boilerplate RN template here https://github.com/facebook/react-native/commit/f3db6cc52792e3006a16408df4ae40f3aee19a86

**Review by trevorrd — APPROVED** [review]

**Comment by trevorrd** [comment]
Can somebody with write access merge this please? Please and thank you! :)

**Comment by trevorrd** [comment]
@philihp --> Do you need to update the package version too?  (i.e. 3.2.2?)

**Comment by philihp** [comment]
> @philihp --> Do you need to update the package version too? (i.e. 3.2.2?)

Yes, please. I think a minor version bump is probably appropriate.

**Review by gksander — APPROVED** [review]

**Pull request merged**
