### PR TITLE
Add accessibility roles found in https://facebook.github.io/react-nat…

### LINKED ISSUE #53: has-valid-accessibility-role lacks several valid accessibility roles
# Actual
`has-valid-accessibility-role` only allows `accessibilityRole` to be one of:
  * adjustable
  * button
  * header
  * image
  * imagebutton
  * keyboardkey
  * link
  * none
  * search
  * summary

when React Native supports 27 `accessibilityRole`s: https://facebook.github.io/react-native/docs/accessibility#accessibilityrole-ios-android

# Expected
`has-valid-accessibility-role` allows all 27 `accessibilityRole`s found on https://facebook.github.io/react-native/docs/accessibility#accessibilityrole-ios-android

By the way, thanks for this package!

Oh! And I'll be more than happy to help out with this pull request once this is confirmed to be a bug and not a feature.

### PR DESCRIPTION
**Pull request by AryanJ-NYC**
…ive/docs/accessibility#accessibilityrole-ios-android

Closes #53

### CODE REVIEW

**Comment by alex-saunders** [comment]
@AryanJ-NYC Thanks so much for this PR! Could you sort out these conflicts? Sorry, I think it's probably just prettier problems..

**Comment by AryanJ-NYC** [comment]
@alex-saunders merge conflicts sorted. Thanks!

**Comment by MoOx** [comment]
Would be nice to have this merged & released. Thanks you for this!

**Comment by alex-saunders** [comment]
Hey @AryanJ-NYC sorry for the delay on this, getting this merged now.
Thanks for your work on this!

**Comment by MoOx** [comment]
Thank you @AryanJ-NYC & @alex-saunders 🙏

**Pull request merged**
