### PR TITLE
Do not require accessibilityRole on components with accessible={false}

### PR DESCRIPTION
**Pull request by draperunner**
If a Touchable has been set to be non-accessible, it is unnecessary to enforce the accessibilityRole prop.

### CODE REVIEW

**Comment by orofbrown** [comment]
LGTM!!! 😁

**Comment by MoOx** [comment]
@draperunner Could you merge conflict?

**Comment by draperunner** [comment]
Done @MoOx

**Comment by MoOx** [comment]
Thanks! Hope that will help to have this merged 🙏

**Comment by draperunner** [comment]
Ah, so you're not a maintainer :P Well, maybe @knitcodemonkey and @alex-saunders just need a friendly ping.

**Pull request merged**
